django_quill/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

playground/config/urls.py
import importlib.util

from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from . import views

__all__ = ("urlpatterns",)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.IndexView.as_view(), name="index"),
    path("reset/", views.ResetView.as_view(), name="reset"),
    path("posts/", include("posts.urls")),
]
urlpatterns_apis = []

if (spec := importlib.util.find_spec("rest_framework")) is not None:
    from posts import apis

    router = SimpleRouter()
    router.register(r"", apis.QuillPostViewSet)
    urlpatterns_apis.append(path("posts/", include(router.urls)))

if urlpatterns_apis:
    urlpatterns.append(path("api/", include(urlpatterns_apis)))

playground/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"
urlpatterns = [
    path("", views.UEPostListView.as_view(), name="ueditor-post-list"),
    path("create/", views.UEPostCreateView.as_view(), name="ueditor-post-create"),
    path(
        "create/normal/",
        views.UEFieldFormView.as_view(),
        name="ueditor-post-create-normal",
    ),
    path(
        "create/normal/html/",
        views.UEFieldFormHtmlInitialView.as_view(),
        name="ueditor-post-create-normal-html",
    ),
    path(
        "create/normal/text/",
        views.UEFieldFormTextInitialView.as_view(),
        name="ueditor-post-create-normal-text",
    ),
    path("<int:pk>/", views.UEPostDetailView.as_view(), name="ueditor-post-detail"),
    path(
        "<int:pk>/update/",
        views.UEPostUpdateView.as_view(),
        name="ueditor-post-update",
    ),
]

testproject/post/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.QuillPostListView.as_view(), name='quill-post-list'),
    path('create/', views.QuillPostCreateView.as_view(), name='quill-post-create'),
    path('create/normal/', views.QuillFieldFormView.as_view(), name='quill-post-create-normal'),
    path('create/normal/html/', views.QuillFieldFormHtmlInitialView.as_view(), name='quill-post-create-normal-html'),
    path('create/normal/text/', views.QuillFieldFormTextInitialView.as_view(), name='quill-post-create-normal-text'),
    path('<int:pk>/', views.QuillPostDetailView.as_view(), name='quill-post-detail'),
    path('<int:pk>/update/', views.QuillPostUpdateView.as_view(), name='quill-post-update')
]

playground/posts/models.py
from django.db import models
from django.db.models import CharField, TextField
from django.urls import reverse

from django_quill.fields import QuillField

__all__ = (
    "QuillPost",
    "NonQuillPost",
)


class QuillPost(models.Model):
    content = QuillField()

    class Meta:
        ordering = ["-pk"]

    def get_absolute_url(self):
        return reverse("posts:quill-post-detail", args=[self.pk])


class NonQuillPost(models.Model):
    content_char = CharField(max_length=300, blank=True)
    content_text = TextField(blank=True)

testproject/post/models.py
from django.db import models
from django.urls import reverse

from django_quill.fields import QuillField


class QuillPost(models.Model):
    content = QuillField()

    class Meta:
        ordering = ['-pk']

    def get_absolute_url(self):
        return reverse('posts:quill-post-detail', args=[self.pk])


class QuillMaster(models.Model):
    name = models.CharField(max_length=64)


class QuillDetail(models.Model):
    master = models.ForeignKey(QuillMaster, on_delete=models.CASCADE)
    content = QuillField()


class QuillDetail2(models.Model):
    master = models.ForeignKey(QuillMaster, on_delete=models.CASCADE)
    content = QuillField()

playground/posts/forms.py
from django import forms

from django_ueditor.forms import UEFormField
from .models import UEPost

__all__ = (
    "UEFieldForm",
    "UEPostForm",
)


class UEFieldForm(forms.Form):
    content = UEFormField()

    def save(self):
        return UEPost.objects.create(content=self.cleaned_data["content"])


class UEPostForm(forms.ModelForm):
    class Meta:
        model = UEPost
        fields = ("content",)

testproject/post/forms.py
from django import forms

from django_quill.forms import QuillFormField
from .models import QuillPost


class QuillFieldForm(forms.Form):
    content = QuillFormField()

    def save(self):
        return QuillPost.objects.create(content=self.cleaned_data['content'])


class QuillPostForm(forms.ModelForm):
    class Meta:
        model = QuillPost
        fields = (
            'content',
        )

playground/posts/views.py
from django.conf import settings
from django.urls import reverse
from django.views.generic import ListView, UpdateView, DetailView, FormView, CreateView

from .forms import UEFieldForm, UEPostForm
from .models import UEPost

__all__ = (
    "UEPostListView",
    "UEPostCreateView",
    "UEPostDetailView",
    "UEPostUpdateView",
    "UEFieldFormView",
    "UEFieldFormHtmlInitialView",
    "UEFieldFormTextInitialView",
)

HTML_INITIAL = f"""
<h1><strong>django-ueditor-editor</strong></h1>
<br>
<p>django-ueditor-editor makes&nbsp;UE.js&nbsp;easy to use on Django Forms and admin sites</p>
<ul>
    <li><strong>No configuration required for static files!</strong></li>
    <li>The entire code for inserting WYSIWYG editor is less than 30 lines</li>
    <li>It can be used in both admin and Django views</li>
</ul>
<p>
<img src="{settings.TITLE_IMG}"></p>
<ul>
    <li><a href="https://django-ueditor-editor.readthedocs.io/en/latest/pages/using-in-admin.html" rel="noopener noreferrer" target="_blank" style="color: rgb(41, 128, 185);">Using in Django admin</a></li>
    <li><a href="https://django-ueditor-editor.readthedocs.io/en/latest/pages/using-as-form.html" rel="noopener noreferrer" target="_blank" style="color: rgb(41, 128, 185);">Using as Form</a></li>
    <li><a href="https://django-ueditor-editor.readthedocs.io/en/latest/pages/using-as-modelform.html" rel="noopener noreferrer" target="_blank" style="color: rgb(41, 128, 185);">Using as ModelForm</a></li>
    <li><a href="https://django-ueditor-editor.readthedocs.io/en/latest/pages/change-toolbar-configs.html" rel="noopener noreferrer" target="_blank" style="color: rgb(41, 128, 185);">Change toolbar config</a></li>
</ul>
<br>
<h2><strong>Installation</strong></h2>
<p>Use pip to install from PyPI:</p>
<pre class="ql-syntax" spellcheck="false">
    <span class="hljs-attribute">pip</span> install django-ueditor-editor
</pre>
<br>
<p>Add&nbsp;<strong>django_ueditor</strong>&nbsp;to&nbsp;<strong>INSTALLED_APPS</strong>&nbsp;in&nbsp;<strong>settings.py</strong>:</p>
<pre class="ql-syntax" spellcheck="false">
<span class="hljs-attr">INSTALLED_APPS</span> = [
    <span class="hljs-string">'django.contrib.admin'</span>,
    ...
    <span class="hljs-string">'django_ueditor'</span>,
]
</pre>
<br>
<h2><strong>Contributing</strong></h2>
<p>To contribute to&nbsp;<strong>django-ueditor-editor</strong>&nbsp;<a href="https://github.com/leehanyeong/django-ueditor-editor" rel="noopener noreferrer" target="_blank" style="color: rgb(41, 128, 185);">create a fork</a>&nbsp;on GitHub. Clone your fork, make some changes, and submit a pull request.</p>
<br>
<h2><strong>Issues</strong></h2>
<p>Use the GitHub&nbsp;<a href="https://github.com/leehanyeong/django-ueditor-editor/issues" rel="noopener noreferrer" target="_blank" style="color: rgb(41, 128, 185);">issue tracker</a>&nbsp;for&nbsp;<strong>django-ueditor-editor</strong>&nbsp;to submit bugs, issues, and feature requests.</p>"""


class UEPostListView(ListView):
    model = UEPost


class UEPostCreateView(CreateView):
    form_class = UEPostForm
    template_name = "posts/ueditorpost_create.html"


class UEPostDetailView(DetailView):
    model = UEPost


class UEPostUpdateView(UpdateView):
    model = UEPost
    fields = ["content"]


# NormalForm
class UEFieldFormView(FormView):
    form_class = UEFieldForm
    template_name = "posts/ueditorpost_normal_form.html"

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("posts:ueditor-post-detail", args=(self.object.pk,))


class UEFieldFormHtmlInitialView(UEFieldFormView):
    initial = {
        "content": HTML_INITIAL,
    }


class UEFieldFormTextInitialView(UEFieldFormView):
    initial = {
        "content": "django-ueditor-editor makes UE.js easy to use on Django Forms and admin sites",
    }

testproject/post/views.py
from django.conf import settings
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, UpdateView, DetailView, FormView, CreateView, View

from .forms import QuillFieldForm, QuillPostForm
from .models import QuillPost

__all__ = (
    'QuillPostListView',
    'QuillPostCreateView',
    'QuillPostDetailView',
    'QuillPostUpdateView',
    'QuillFieldFormView',
    'QuillFieldFormHtmlInitialView',
    'QuillFieldFormTextInitialView',
)


class QuillPostListView(ListView):
    model = QuillPost


class QuillPostCreateView(CreateView):
    form_class = QuillPostForm
    template_name = 'post/quillpost_create.html'


class QuillPostDetailView(DetailView):
    model = QuillPost


class QuillPostUpdateView(UpdateView):
    model = QuillPost
    fields = ['content']


# NormalForm
class QuillFieldFormView(FormView):
    form_class = QuillFieldForm
    template_name = 'post/quillpost_normal_form.html'

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('posts:quill-post-detail', args=(self.object.pk,))


class QuillFieldFormHtmlInitialView(QuillFieldFormView):
    initial = {
        'content': f'<h1>django-quill-editor</h1><br>'
                   f'<img src="{settings.TITLE_IMG}">',
    }


class QuillFieldFormTextInitialView(QuillFieldFormView):
    initial = {
        'content': 'django-quill-editor makes Quill.js easy to use on Django Forms and admin sites',
    }


'''
Django Index views
'''
class IndexView(CreateView):
    template_name = 'index.html'
    form_class = QuillPostForm
    success_url = reverse_lazy('post:quill-post-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['normal_form'] = QuillFieldForm()
        context['title_img'] = settings.TITLE_IMG
        return context


class ResetView(View):
    def post(self, request):
        QuillPost.objects.all().delete()
        return redirect(reverse('post:quill-post-list'))

testproject/post/templates/post/base_posts.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row mb-2">
            <div class="col-12 col-md-3 col-lg-3">
                <h3>{% block title %}title{% endblock %}</h3>
            </div>
            <div class="col-12 col-md-9 col-lg-9">
                <div class="d-flex justify-content-end">
                    <form action="{% url 'reset' %}" method="POST">{% csrf_token %}
                        <button type="submit" class="btn btn-danger mr-4">Delete all posts</button>
                    </form>
                    <a href="{% url 'posts:quill-post-create-normal' %}" class="btn btn-primary mr-1">Form</a>
                    <a href="{% url 'posts:quill-post-create' %}" class="btn btn-primary mr-1">ModelForm</a>
                    <a href="{% url 'posts:quill-post-create-normal-html' %}" class="btn btn-primary mr-1">Form (Initial HTML)</a>
                    <a href="{% url 'posts:quill-post-create-normal-text' %}" class="btn btn-primary mr-1">Form (Initial Text)</a>
                </div>
            </div>
        </div>
        {% block posts_content %}
        {% endblock %}
    </div>
{% endblock %}

testproject/post/templates/post/quillpost.html
<div class="card">
    <div class="card-body">
        <div>
            {{ post.content.html|safe }}
        </div>
        <a href="{% url 'posts:quill-post-update' pk=post.pk %}" class="btn btn-primary btn-sm">EDIT</a>
    </div>
</div>

testproject/post/templates/post/quillpost_create.html
{% extends 'post/base_posts.html' %}

{% block title %}Post Create (ModelForm){% endblock %}
{% block posts_content %}
    <form action="" method="POST">{% csrf_token %}
        {{ form.content }}
        <button type="submit" class="btn btn-primary btn-block mt-1">Create</button>
    </form>
{% endblock %}

testproject/post/templates/post/quillpost_detail.html
{% extends 'post/base_posts.html' %}

{% block title %}Post Detail (pk: {{ object.pk }}){% endblock %}
{% block posts_content %}
    {% include 'post/quillpost.html' with post=object %}
{% endblock %}

testproject/post/templates/post/quillpost_form.html
{% extends 'post/base_posts.html' %}

{% block title %}Post Update (pk: {{ object.pk }}){% endblock %}
{% block posts_content %}
    <div><a href="{% url 'posts:quill-post-detail' pk=object.pk %}" class="btn btn-primary btn-sm">◀ Back to Detail</a></div>
    <div class="mt-2">
        <form action="" method="POST">{% csrf_token %}
            {{ form.content }}
            <button type="submit" class="btn btn-primary btn-block mt-1">Update Post</button>
        </form>
    </div>
{% endblock %}

testproject/post/templates/post/quillpost_list.html
{% extends 'post/base_posts.html' %}

{% block title %}Post List{% endblock %}
{% block posts_content %}
    <div class="row">
        <div class="col">
            {% if object_list %}
                {% for post in object_list %}
                    {% include 'post/quillpost.html' with post=post %}
                    {% if not forloop.last %}
                        <hr>{% endif %}
                {% endfor %}
            {% else %}
                <p>There is no post.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

testproject/post/templates/post/quillpost_normal_form.html
{% extends 'post/base_posts.html' %}

{% block title %}Post Create (NormalForm){% endblock %}
{% block posts_content %}
    <form action="" method="POST">{% csrf_token %}
        {{ form.content }}
        <button type="submit" class="btn btn-primary btn-block mt-1">Create</button>
    </form>
{% endblock %}