django_quill/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

playground/config/urls.py
import importlib.util

from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from . import views

__all__ = ("urlpatterns",)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.IndexView.as_view(), name="index"),
    path("reset/", views.ResetView.as_view(), name="reset"),
    path("posts/", include("posts.urls")),
]
urlpatterns_apis = []

if (spec := importlib.util.find_spec("rest_framework")) is not None:
    from posts import apis

    router = SimpleRouter()
    router.register(r"", apis.QuillPostViewSet)
    urlpatterns_apis.append(path("posts/", include(router.urls)))

if urlpatterns_apis:
    urlpatterns.append(path("api/", include(urlpatterns_apis)))

playground/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"
urlpatterns = [
    path("", views.UEPostListView.as_view(), name="ueditor-post-list"),
    path("create/", views.UEPostCreateView.as_view(), name="ueditor-post-create"),
    path(
        "create/normal/",
        views.UEFieldFormView.as_view(),
        name="ueditor-post-create-normal",
    ),
    path(
        "create/normal/html/",
        views.UEFieldFormHtmlInitialView.as_view(),
        name="ueditor-post-create-normal-html",
    ),
    path(
        "create/normal/text/",
        views.UEFieldFormTextInitialView.as_view(),
        name="ueditor-post-create-normal-text",
    ),
    path("<int:pk>/", views.UEPostDetailView.as_view(), name="ueditor-post-detail"),
    path(
        "<int:pk>/update/",
        views.UEPostUpdateView.as_view(),
        name="ueditor-post-update",
    ),
]

testproject/post/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.QuillPostListView.as_view(), name='quill-post-list'),
    path('create/', views.QuillPostCreateView.as_view(), name='quill-post-create'),
    path('create/normal/', views.QuillFieldFormView.as_view(), name='quill-post-create-normal'),
    path('create/normal/html/', views.QuillFieldFormHtmlInitialView.as_view(), name='quill-post-create-normal-html'),
    path('create/normal/text/', views.QuillFieldFormTextInitialView.as_view(), name='quill-post-create-normal-text'),
    path('<int:pk>/', views.QuillPostDetailView.as_view(), name='quill-post-detail'),
    path('<int:pk>/update/', views.QuillPostUpdateView.as_view(), name='quill-post-update')
]

playground/posts/models.py
from django.db import models
from django.db.models import CharField, TextField
from django.urls import reverse

from django_quill.fields import QuillField

__all__ = (
    "QuillPost",
    "NonQuillPost",
)


class QuillPost(models.Model):
    content = QuillField()

    class Meta:
        ordering = ["-pk"]

    def get_absolute_url(self):
        return reverse("posts:quill-post-detail", args=[self.pk])


class NonQuillPost(models.Model):
    content_char = CharField(max_length=300, blank=True)
    content_text = TextField(blank=True)

testproject/post/models.py
from django.db import models
from django.urls import reverse

from django_quill.fields import QuillField


class QuillPost(models.Model):
    content = QuillField()

    class Meta:
        ordering = ['-pk']

    def get_absolute_url(self):
        return reverse('posts:quill-post-detail', args=[self.pk])


class QuillMaster(models.Model):
    name = models.CharField(max_length=64)


class QuillDetail(models.Model):
    master = models.ForeignKey(QuillMaster, on_delete=models.CASCADE)
    content = QuillField()


class QuillDetail2(models.Model):
    master = models.ForeignKey(QuillMaster, on_delete=models.CASCADE)
    content = QuillField()

playground/posts/forms.py
from django import forms

from django_ueditor.forms import UEFormField
from .models import UEPost

__all__ = (
    "UEFieldForm",
    "UEPostForm",
)


class UEFieldForm(forms.Form):
    content = UEFormField()

    def save(self):
        return UEPost.objects.create(content=self.cleaned_data["content"])


class UEPostForm(forms.ModelForm):
    class Meta:
        model = UEPost
        fields = ("content",)

testproject/post/forms.py
from django import forms

from django_quill.forms import QuillFormField
from .models import QuillPost


class QuillFieldForm(forms.Form):
    content = QuillFormField()

    def save(self):
        return QuillPost.objects.create(content=self.cleaned_data['content'])


class QuillPostForm(forms.ModelForm):
    class Meta:
        model = QuillPost
        fields = (
            'content',
        )

playground/posts/views.py
from django.conf import settings
from django.urls import reverse
from django.views.generic import ListView, UpdateView, DetailView, FormView, CreateView

from .forms import UEFieldForm, UEPostForm
from .models import UEPost

__all__ = (
    "UEPostListView",
    "UEPostCreateView",
    "UEPostDetailView",
    "UEPostUpdateView",
    "UEFieldFormView",
    "UEFieldFormHtmlInitialView",
    "UEFieldFormTextInitialView",
)

HTML_INITIAL = f"""
<h1><strong>django-ueditor-editor</strong></h1>
<br>
<p>django-ueditor-editor makes&nbsp;UE.js&nbsp;easy to use on Django Forms and admin sites</p>
<ul>
    <li><strong>No configuration required for static files!</strong></li>
    <li>The entire code for inserting WYSIWYG editor is less than 30 lines</li>
    <li>It can be used in both admin and Django views</li>
</ul>
<p>
<img src="{settings.TITLE_IMG}"></p>
<ul>
    <li><a href="https://django-ueditor-editor.readthedocs.io/en/latest/pages/using-in-admin.html" rel="noopener noreferrer" target="_blank" style="color: rgb(41, 128, 185);">Using in Django admin</a></li>
    <li><a href="https://django-ueditor-editor.readthedocs.io/en/latest/pages/using-as-form.html" rel="noopener noreferrer" target="_blank" style="color: rgb(41, 128, 185);">Using as Form</a></li>
    <li><a href="https://django-ueditor-editor.readthedocs.io/en/latest/pages/using-as-modelform.html" rel="noopener noreferrer" target="_blank" style="color: rgb(41, 128, 185);">Using as ModelForm</a></li>
    <li><a href="https://django-ueditor-editor.readthedocs.io/en/latest/pages/change-toolbar-configs.html" rel="noopener noreferrer" target="_blank" style="color: rgb(41, 128, 185);">Change toolbar config</a></li>
</ul>
<br>
<h2><strong>Installation</strong></h2>
<p>Use pip to install from PyPI:</p>
<pre class="ql-syntax" spellcheck="false">
    <span class="hljs-attribute">pip</span> install django-ueditor-editor
</pre>
<br>
<p>Add&nbsp;<strong>django_ueditor</strong>&nbsp;to&nbsp;<strong>INSTALLED_APPS</strong>&nbsp;in&nbsp;<strong>settings.py</strong>:</p>
<pre class="ql-syntax" spellcheck="false">
<span class="hljs-attr">INSTALLED_APPS</span> = [
    <span class="hljs-string">'django.contrib.admin'</span>,
    ...
    <span class="hljs-string">'django_ueditor'</span>,
]
</pre>
<br>
<h2><strong>Contributing</strong></h2>
<p>To contribute to&nbsp;<strong>django-ueditor-editor</strong>&nbsp;<a href="https://github.com/leehanyeong/django-ueditor-editor" rel="noopener noreferrer" target="_blank" style="color: rgb(41, 128, 185);">create a fork</a>&nbsp;on GitHub. Clone your fork, make some changes, and submit a pull request.</p>
<br>
<h2><strong>Issues</strong></h2>
<p>Use the GitHub&nbsp;<a href="https://github.com/leehanyeong/django-ueditor-editor/issues" rel="noopener noreferrer" target="_blank" style="color: rgb(41, 128, 185);">issue tracker</a>&nbsp;for&nbsp;<strong>django-ueditor-editor</strong>&nbsp;to submit bugs, issues, and feature requests.</p>"""


class UEPostListView(ListView):
    model = UEPost


class UEPostCreateView(CreateView):
    form_class = UEPostForm
    template_name = "posts/ueditorpost_create.html"


class UEPostDetailView(DetailView):
    model = UEPost


class UEPostUpdateView(UpdateView):
    model = UEPost
    fields = ["content"]


# NormalForm
class UEFieldFormView(FormView):
    form_class = UEFieldForm
    template_name = "posts/ueditorpost_normal_form.html"

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("posts:ueditor-post-detail", args=(self.object.pk,))


class UEFieldFormHtmlInitialView(UEFieldFormView):
    initial = {
        "content": HTML_INITIAL,
    }


class UEFieldFormTextInitialView(UEFieldFormView):
    initial = {
        "content": "django-ueditor-editor makes UE.js easy to use on Django Forms and admin sites",
    }

testproject/post/views.py
from django.conf import settings
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, UpdateView, DetailView, FormView, CreateView, View

from .forms import QuillFieldForm, QuillPostForm
from .models import QuillPost

__all__ = (
    'QuillPostListView',
    'QuillPostCreateView',
    'QuillPostDetailView',
    'QuillPostUpdateView',
    'QuillFieldFormView',
    'QuillFieldFormHtmlInitialView',
    'QuillFieldFormTextInitialView',
)


class QuillPostListView(ListView):
    model = QuillPost


class QuillPostCreateView(CreateView):
    form_class = QuillPostForm
    template_name = 'post/quillpost_create.html'


class QuillPostDetailView(DetailView):
    model = QuillPost


class QuillPostUpdateView(UpdateView):
    model = QuillPost
    fields = ['content']


# NormalForm
class QuillFieldFormView(FormView):
    form_class = QuillFieldForm
    template_name = 'post/quillpost_normal_form.html'

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('posts:quill-post-detail', args=(self.object.pk,))


class QuillFieldFormHtmlInitialView(QuillFieldFormView):
    initial = {
        'content': f'<h1>django-quill-editor</h1><br>'
                   f'<img src="{settings.TITLE_IMG}">',
    }


class QuillFieldFormTextInitialView(QuillFieldFormView):
    initial = {
        'content': 'django-quill-editor makes Quill.js easy to use on Django Forms and admin sites',
    }


'''
Django Index views
'''
class IndexView(CreateView):
    template_name = 'index.html'
    form_class = QuillPostForm
    success_url = reverse_lazy('post:quill-post-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['normal_form'] = QuillFieldForm()
        context['title_img'] = settings.TITLE_IMG
        return context


class ResetView(View):
    def post(self, request):
        QuillPost.objects.all().delete()
        return redirect(reverse('post:quill-post-list'))

testproject/post/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <!-- django-quill-editor Media -->
  {% include 'django_quill/media.html' %}

  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <title>django-quill-editor</title>
</head>
<body>
<div id="wrap">
  <nav class="navbar navbar-expand navbar-dark bg-primary mb-2">
    <a href="{% url 'index' %}" class="navbar-brand">django-quill-editor</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="w-100">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url 'posts:quill-post-list' %}" class="nav-link">Example</a>
        </li>
        <li class="nav-item mr-auto">
          <a href="{% url 'admin:index' %}" class="nav-link" target="_blank">DjangoAdmin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://github.com/LeeHanYeong/django-quill-editor" target="_blank">Repository</a>
        </li>
      </ul>
    </div>
  </nav>
  {% block content %}
  {% endblock %}
  <footer class="mt-2 text-center">© 2020 ~ 2021 <a href="https://github.com/leehanyeong" target="_blank">leehanyeong</a></footer>

  {% block script %}
  {% endblock %}
</div>
</body>
</html>

testproject/post/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <h2>django-quill-editor</h2>
        <p>
            <img alt="PyPI" src="https://img.shields.io/pypi/v/django-quill-editor">
        </p>
        <p>
            <a href="https://github.com/LeeHanYeong/django-quill-editor" target="_blank">django-quill-editor</a> makes <a href="https://quilljs.com/" target="_blank">Quill.js</a> easy to use on Django Forms and admin sites
        </p>
        <ul>
            <li><b>No configuration required for static files!</b></li>
            <li>The entire code for inserting WYSIWYG editor is less than 30 lines</li>
            <li>It can be used in both admin and Django views</li>
        </ul>
        <img src="{{ title_img }}" style="max-width: 400px;" alt="">
        <hr>

        <h3>Form and ModelForm</h3>
        <p style="white-space: pre-line">You can display the editor using quill.js in the template using Form or ModelForm.
            When displaying HTML content, not the editor, use the <b>.html</b> property</p>
        <p>
            <a href="{% url 'posts:quill-post-list' %}">Go to Example ▶</a>
        </p>

        <h3>Django admin</h3>
        <p style="white-space: pre-line">You can easily integrate with django admin.
            In this playground, you can use admin without credentials.
        <p>
            <a href="{% url 'admin:index' %}">Go to Django admin ▶</a>
        </p>
    </div>
{% endblock %}